language: android
dist: bionic

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake"
  - echo y | sdkmanager "lldb;3.1"

