language: android
dist: bionic

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-28
    - ndk-bundle
    - cmake
    - lldb

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'platforms;android-.+'
    - 'build-tools;.+'
