name: Build and test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Prepare caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            !~/.gradle/caches/modules-2/modules-2.lock
            !~/.gradle/caches/*/plugin-resolution/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install Android SDK
        uses: kineticengines/setup-android-actions@v0.1
        
      - name: Install Android SDK components
        env:
          ANDROID_API_LEVEL: '29'
          ANDROID_BUILD_TOOLS_VERSION: '29.0.3'
          NDK_VERSION: '21.0.6113669'
          CMAKE_VERSION: '3.10.2.4988404'
        run: |
          yes | sdkmanager 'tools'
          yes | sdkmanager 'platform-tools'
          yes | sdkmanager 'build-tools-$ANDROID_BUILD_TOOLS_VERSION'
          yes | sdkmanager 'android-$ANDROID_API_LEVEL'
          yes | sdkmanager 'extra-android-m2repository'
          yes | sdkmanager 'extra-google-m2repository'
          yes | sdkmanager 'ndk-bundle'
          yes | sdkmanager 'ndk;$NDK_VERSION'
          yes | sdkmanager 'cmake;$CMAKE_VERSION'
      
      - name: Build and test application
        run: |
          ./gradlew build assembleDebug test





