name: Lint

on:
  push:
     paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Checkout repo'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: 'Run lint'
        run: ./gradlew lint

      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: build/reports/lint-results.xml
