name: Validate pull request quality

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Checkout pull request base reference
        run: ./ci-scripts/clone_base_ref.sh
      
      - name: Validate pull request quality
        run: ./ci-scripts/validate_pr_changes.py




